import { OrcaData } from './types'

export function seed(): OrcaData {
  return {
    user: {
      name: 'Demo User',
      email: 'demo@orca.app',
      onboarded: true,
      employmentType: 'employed',
      payFreq: 'biweekly',
      payCycle: 'standard',
      payRate: '18',
      hoursPerDay: '8',
      nextPay: '2025-01-20',
      creditScore: 648,
      utilization: 35,
      onTime: 98,
      acctAge: 8,
      inquiries: 1,
      totalDebt: 4200,
      creditLimit: 12000,
      scoreHistory: [
        { m: 'Jan', s: 640 },
        { m: 'Feb', s: 645 },
        { m: 'Mar', s: 648 },
      ],
    },
    income: [
      {
        id: 'inc1',
        name: 'Full-time Job',
        amount: 1440,
        freq: 'weekly',
        active: true,
      },
    ],
    bills: [
      {
        id: 'bill1',
        name: 'Rent',
        amount: 1200,
        cat: 'Rent/Mortgage',
        due: '2025-01-01',
        freq: 'monthly',
        recurrence: 'monthly',
        status: 'upcoming',
        alloc: [],
      },
      {
        id: 'bill2',
        name: 'Electric Bill',
        amount: 120,
        cat: 'Utilities',
        due: '2025-01-15',
        freq: 'monthly',
        recurrence: 'monthly',
        status: 'upcoming',
        alloc: [],
      },
      {
        id: 'bill3',
        name: 'Internet',
        amount: 60,
        cat: 'Phone/Internet',
        due: '2025-01-10',
        freq: 'monthly',
        recurrence: 'monthly',
        status: 'upcoming',
        alloc: [],
      },
      {
        id: 'bill4',
        name: 'Car Insurance',
        amount: 95,
        cat: 'Insurance',
        due: '2025-01-20',
        freq: 'monthly',
        recurrence: 'monthly',
        status: 'upcoming',
        alloc: [],
      },
      {
        id: 'bill5',
        name: 'Credit Card',
        amount: 150,
        cat: 'Debt/Credit Cards',
        due: '2025-01-25',
        freq: 'monthly',
        recurrence: 'monthly',
        status: 'upcoming',
        alloc: [],
      },
      {
        id: 'bill6',
        name: 'Spotify',
        amount: 12,
        cat: 'Subscriptions',
        due: '2025-01-05',
        freq: 'monthly',
        recurrence: 'monthly',
        status: 'paid',
        alloc: [],
      },
      {
        id: 'bill7',
        name: 'Car Payment',
        amount: 350,
        cat: 'Car Note',
        due: '2025-01-12',
        freq: 'monthly',
        recurrence: 'monthly',
        status: 'upcoming',
        alloc: [],
      },
    ],
    expenses: [
      {
        id: 'exp1',
        name: 'Grocery Shopping',
        amount: 85.50,
        cat: 'Groceries',
        date: '2025-01-08',
      },
      {
        id: 'exp2',
        name: 'Gas',
        amount: 45.00,
        cat: 'Gas/Transport',
        date: '2025-01-07',
      },
      {
        id: 'exp3',
        name: 'Coffee',
        amount: 6.50,
        cat: 'Dining Out',
        date: '2025-01-09',
      },
      {
        id: 'exp4',
        name: 'Movie Tickets',
        amount: 28.00,
        cat: 'Entertainment',
        date: '2025-01-06',
      },
    ],
    goals: [
      {
        id: 'goal1',
        name: 'Emergency Fund',
        target: 5000,
        current: 2150,
        date: '2025-12-31',
        cType: 'fixed',
        cVal: 250,
        active: true,
      },
      {
        id: 'goal2',
        name: 'Vacation Fund',
        target: 2000,
        current: 650,
        date: '2025-08-31',
        cType: 'percent',
        cVal: 5,
        active: true,
      },
    ],
    splitMode: 'none',
    notifs: [
      {
        id: 'notif1',
        type: 'bill',
        title: 'Rent Due Soon',
        body: 'Your rent of $1,200 is due on Jan 1st',
        read: false,
      },
    ],
    groups: [
      {
        id: 'group1',
        name: 'Trip Fund',
        goal: 'Save for group trip',
        target: 5000,
        current: 2300,
        date: '2025-06-30',
        code: 'TRP001',
        members: [
          {
            id: 'mem1',
            name: 'You',
            role: 'admin',
            target: 1250,
            contrib: 800,
            balance: 450,
          },
          {
            id: 'mem2',
            name: 'Alex',
            role: 'member',
            target: 1250,
            contrib: 750,
            balance: 500,
          },
          {
            id: 'mem3',
            name: 'Jordan',
            role: 'member',
            target: 1250,
            contrib: 750,
            balance: 500,
          },
        ],
        activity: [
          {
            id: 'act1',
            user: 'You',
            msg: 'Contributed $800',
            date: '2025-01-08',
          },
        ],
      },
    ],
    rent: [
      {
        id: 'rent1',
        month: 'December',
        amount: 1200,
        status: 'paid',
        reported: true,
        rDate: '2024-12-01',
      },
      {
        id: 'rent2',
        month: 'January',
        amount: 1200,
        status: 'pending',
        reported: false,
        rDate: null,
      },
      {
        id: 'rent3',
        month: 'February',
        amount: 1200,
        status: 'upcoming',
        reported: false,
        rDate: null,
      },
    ],
    plaid: null,
    roommates: {
      enabled: false,
      totalRent: 0,
      utilities: [],
      members: [],
      history: [],
    },
  }
}
